# Whether the player has to look up to go up. if false, they use space and shift instead
fly-lookup: true
# enable this to stop people from exiting the car while its in the air. Applies to flying cars only
dismount-air: false
# The amount of fuel added to the car at a time when riding
fuel-per-click: 32