name: FloatingCars
main: com.SimplyBallistic.FloatingCars.FCMain
version: 1.04
description:  Cars...that hover!
author: SimplyBallistic
api-version: 1.13
commands:
   spacecar:
      description: Spacecars
      usage: /<command> 
      permission: fc.commands
      aliases: [spacec,sc,spaceship,car,cars]
