name: FloatingCars
main: com.SimplyBallistic.FloatingCars.FCMain
version: 1.03
description:  Cars...that hover!
author: SimplyBallistic
commands:
   spacecar:
      description: Spacecars
      usage: /<command> 
      permission: fc.commands
      aliases: [spacec,sc,spaceship,car,cars]
