name: FloatingCars
main: com.SimplyBallistic.FloatingCars.FCMain
version: 1.02
description:  Cars...that hover!
author: xBallisticBlazex
softdepend: [ZotBox,ZotLib]
commands:
   spacecar:
      description: Spacecars
      usage: /<command> 
      permission: fc.commands
      aliases: [spacec,sc,spaceship,car,cars]