# Whether the player has to look up to go up. if false, they use space and shift instead
fly-lookup: false
# enable this to stop people from exiting the car while its in the air. Applies to flying cars only
dismount-air: false
# The hover height of the hover car
hover-height: 1
# The amount of fuel to add at a time while flying
fuel-per-click: 10