name: FloatingCars
main: com.SimplyBallistic.FloatingCars.FCMain
version: 1.01
description:  Cars...that hover!
author: xBallisticBlazex
softdepend: [ZotLib]
commands:
   spacecar:
      description: Spacecars
      usage: /<command> 
      permission: fc.spacecar
      aliases: [spacec,sc]